<?php

// Maps football-data.co.uk CSV team names (exact, case-sensitive)
// to the canonical teams.name in the database.
// Only teams whose CSV name differs from the canonical name need an entry.
// Teams with no alias are matched via exact teams.name lookup.

return [
    'Atalanta'   => 'Atalanta BC',
    'Bologna'    => 'Bologna FC 1909',
    'Cagliari'   => 'Cagliari Calcio',
    'Como'       => 'Como 1907',
    'Cremonese'  => 'US Cremonese',
    'Empoli'     => 'Empoli FC',
    'Fiorentina' => 'ACF Fiorentina',
    'Frosinone'  => 'Frosinone Calcio',
    'Genoa'      => 'Genoa CFC',
    'Inter'      => 'FC Internazionale Milano',
    'Juventus'   => 'Juventus FC',
    'Lazio'      => 'SS Lazio',
    'Lecce'      => 'US Lecce',
    'Milan'      => 'AC Milan',
    'Monza'      => 'AC Monza',
    'Napoli'     => 'SSC Napoli',
    'Parma'      => 'Parma Calcio 1913',
    'Pisa'       => 'AC Pisa 1909',
    'Roma'       => 'AS Roma',
    'Salernitana' => 'US Salernitana 1919',
    'Sassuolo'   => 'US Sassuolo Calcio',
    'Torino'     => 'Torino FC',
    'Udinese'    => 'Udinese Calcio',
    'Venezia'    => 'Venezia FC',
    'Verona'     => 'Hellas Verona FC',

    // Premier League (England)
    'Arsenal'        => 'Arsenal FC',
    'Aston Villa'    => 'Aston Villa FC',
    'Bournemouth'    => 'AFC Bournemouth',
    'Brentford'      => 'Brentford FC',
    'Brighton'       => 'Brighton & Hove Albion FC',
    'Chelsea'        => 'Chelsea FC',
    'Crystal Palace' => 'Crystal Palace FC',
    'Everton'        => 'Everton FC',
    'Fulham'         => 'Fulham FC',
    'Ipswich'        => 'Ipswich Town FC',
    'Leeds'          => 'Leeds United FC',
    'Leicester'      => 'Leicester City FC',
    'Liverpool'      => 'Liverpool FC',
    'Luton'          => 'Luton Town FC',
    'Man City'       => 'Manchester City FC',
    'Man United'     => 'Manchester United FC',
    'Newcastle'      => 'Newcastle United FC',
    "Nott'm Forest"  => 'Nottingham Forest FC',
    'Sheffield United' => 'Sheffield United FC',
    'Southampton'    => 'Southampton FC',
    'Sunderland'     => 'Sunderland AFC',
    'Tottenham'      => 'Tottenham Hotspur FC',
    'Burnley'        => 'Burnley FC',
    'West Ham'       => 'West Ham United FC',
    'Wolves'         => 'Wolverhampton Wanderers FC',

    // La Liga (Spain)
    'Alaves'      => 'Deportivo Alavés',
    'Almeria'     => 'UD Almería',
    'Ath Bilbao'  => 'Athletic Club',
    'Ath Madrid'  => 'Club Atlético de Madrid',
    'Barcelona'   => 'FC Barcelona',
    'Betis'       => 'Real Betis Balompié',
    'Cadiz'       => 'Cádiz CF',
    'Celta'       => 'RC Celta de Vigo',
    'Elche'       => 'Elche CF',
    'Espanol'     => 'RCD Espanyol de Barcelona',
    'Getafe'      => 'Getafe CF',
    'Girona'      => 'Girona FC',
    'Granada'     => 'Granada CF',
    'Las Palmas'  => 'UD Las Palmas',
    'Leganes'     => 'CD Leganés',
    'Levante'     => 'Levante UD',
    'Mallorca'    => 'RCD Mallorca',
    'Osasuna'     => 'CA Osasuna',
    'Oviedo'      => 'Real Oviedo',
    'Real Madrid' => 'Real Madrid CF',
    'Sevilla'     => 'Sevilla FC',
    'Sociedad'    => 'Real Sociedad de Fútbol',
    'Valencia'    => 'Valencia CF',
    'Valladolid'  => 'Real Valladolid CF',
    'Vallecano'   => 'Rayo Vallecano de Madrid',
    'Villarreal'  => 'Villarreal CF',

    // Bundesliga (Germany)
    'Augsburg'      => 'FC Augsburg',
    'Bayern Munich' => 'FC Bayern München',
    'Bochum'        => 'VfL Bochum 1848',
    'Darmstadt'     => 'SV Darmstadt 98',
    'Dortmund'      => 'Borussia Dortmund',
    'Ein Frankfurt' => 'Eintracht Frankfurt',
    'FC Koln'       => '1. FC Köln',
    'Freiburg'      => 'SC Freiburg',
    'Hamburg'       => 'Hamburger SV',
    'Heidenheim'    => '1. FC Heidenheim 1846',
    'Hoffenheim'    => 'TSG 1899 Hoffenheim',
    'Leverkusen'    => 'Bayer 04 Leverkusen',
    "M'gladbach"    => 'Borussia Mönchengladbach',
    'Mainz'         => '1. FSV Mainz 05',
    'St Pauli'      => 'FC St. Pauli 1910',
    'Stuttgart'     => 'VfB Stuttgart',
    'Union Berlin'  => '1. FC Union Berlin',
    'Werder Bremen' => 'SV Werder Bremen',
    'Wolfsburg'     => 'VfL Wolfsburg',

    // Ligue 1 (France)
    'Angers'      => 'Angers SCO',
    'Auxerre'     => 'AJ Auxerre',
    'Brest'       => 'Stade Brestois 29',
    'Clermont'    => 'Clermont Foot 63',
    'Le Havre'    => 'Le Havre AC',
    'Lens'        => 'Racing Club de Lens',
    'Lille'       => 'Lille OSC',
    'Lorient'     => 'FC Lorient',
    'Lyon'        => 'Olympique Lyonnais',
    'Marseille'   => 'Olympique de Marseille',
    'Metz'        => 'FC Metz',
    'Monaco'      => 'AS Monaco FC',
    'Montpellier' => 'Montpellier HSC',
    'Nantes'      => 'FC Nantes',
    'Nice'        => 'OGC Nice',
    'Paris SG'    => 'Paris Saint-Germain FC',
    'Reims'       => 'Stade de Reims',
    'Rennes'      => 'Stade Rennais FC 1901',
    'St Etienne'  => 'AS Saint-Étienne',
    'Strasbourg'  => 'RC Strasbourg Alsace',
    'Toulouse'    => 'Toulouse FC',
];
